version: '2'
services:
  bootstrap:
    image: docker-ethereum/ethereum_bootstrap:local
    build:
      context: .
      dockerfile: ./bootstrap/Dockerfile
    container_name: bootstrap
    hostname: bootstrap
    entrypoint: /root/bootup.sh
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./bootstrap/chain/genesis.json:/root/files/genesis.json
      - ./bootstrap/password:/root/files/password
      - ./bootstrap/ethereum/keystore:/root/.ethereum/devchain/keystore
      - ./bootstrap/ethereum/geth:/root/.ethereum/devchain/geth
    links:
      - netstats
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  alpha:
    image: docker-ethereum/ethereum_worker:local
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    links:
      - bootstrap
      - netstats
    volumes:
      - ./bootstrap/chain/genesis.json:/root/files/genesis.json
      - ./bootstrap/password:/root/files/password
      - ./bootstrap/ethereum/keystore:/root/.ethereum/devchain/keystore
    entrypoint: /root/bootup.sh
    command: '--datadir=~/.ethereum/devchain --rpccorsdomain="*" --networkid=456719 --rpc --mine --minerthreads=1 --etherbase=0x007CcfFb7916F37F7AEEf05E8096ecFbe55AFc2f --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303"'
  netstats:
    image: docker-ethereum/ethereum_netstats:local
    build:
      context: .
      dockerfile: ./netstat/Dockerfile
    container_name: netstats
    hostname: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    ports:
      - "3000:3000"
